# Generated by Django 5.2.4 on 2025-07-23 15:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoDDS", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashflowrecord",
            name="created_at",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Дата создания операции"
            ),
        ),
    ]
