# Generated by Django 5.2.4 on 2025-07-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoDDS", "0002_alter_cashflowrecord_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashflowrecord",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удалена"),
        ),
    ]
